# Generated by Django 3.1.4 on 2020-12-14 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Looked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looked', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'looked',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Заголовок статьи')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
                ('date_publish', models.DateTimeField(verbose_name='Дата публикации')),
                ('article_image', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, null=True, verbose_name='Личный статус')),
                ('profile_avatar', models.ImageField(blank=True, default='default_avatar.jpg', null=True, upload_to='')),
                ('date_birthday', models.DateField(null=True, verbose_name='Дата рождения')),
                ('featured_articles_list', models.CharField(max_length=1000, null=True, verbose_name='Избранные статьи')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=40, verbose_name='Автор комментария')),
                ('comment_text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('comment_author_image', models.ImageField(blank=True, default='default_avatar.jpg', upload_to='')),
                ('author_id', models.IntegerField(default=1, verbose_name='Id автора')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.article')),
            ],
        ),
    ]
